### ISSUE TITLE
Task - Create A Filter To Filter Out Specific Places

### ISSUE THREAD

**Issue by mnshishk** [UB-CSE/course-project-a6-teamnosleep#15]
Back-end:

Create a filter method that filters out requested places for the User.

Requested: Entertainment

1. Look for Entertainment tags
2. return all the entertainment places

Test:
1. go through each filtered object
2. check that each object has the appropriate tag and coordinates

returned data can be pushed to the front-end or passed down further to be filtered by range from the User location is it was specified.

**Comment by CaseyRDolan** [comment]
IN the setting menu, give options to the user chose which locations to display.
