### ISSUE TITLE
Task - Search current location

### ISSUE THREAD

**Issue by mnshishk** [UB-CSE/course-project-a6-teamnosleep#22]
Back-end:

Through geolocation, locate the device and return its coordinates.

1. Request device's location. (approve/disapprove)
2. Get the coordinates. (store them; probably return of the function)
3. place them on the map.

Tests:
1. Make sure the access was granted.
2. Make sure the the plotted point matches current location.

**Comment by CaseyRDolan** [comment]
Scan the area around the current location of the user and return data information from the location api
