### ISSUE TITLE
Task - Styling/CSS

### ISSUE THREAD

**Issue by stevoo1999** [UB-CSE/course-project-a6-teamnosleep#25]
Update website visuals by using CSS styling for visual presentation.

Acceptance Test:

1.  Functionality is maintained.
2.  Labels and web descriptions appear in the correct place.
3.  Organization is kept.

**Comment by priyanshu0405** [comment]
@stevoo1999, Is this a personal project or the issue is open for anyone?

**Comment by stevoo1999** [comment]
- Updated left side bar. This worked on the third acceptance test to make sure organization was kept. 
- Worked on adding the arrival time to the bottom of the web app and directions to the top of the web app. This worked on the 2nd acceptance test.

**Comment by stevoo1999** [comment]
The left and right side bars can now pop in and out which works with maintaining functionality as stated by the first acceptance test
